// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7xx4axqEDqEd2pVzCtbmDm0AyLM2-7YE',
    appId: '1:357686625509:web:3e911133026229b40d800c',
    messagingSenderId: '357686625509',
    projectId: 'todolist-ed4ba',
    authDomain: 'todolist-ed4ba.firebaseapp.com',
    storageBucket: 'todolist-ed4ba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA18NizlxdcpsZAsUQMsrOysSoV8m_tYKQ',
    appId: '1:357686625509:android:ebdaf1949f9cad540d800c',
    messagingSenderId: '357686625509',
    projectId: 'todolist-ed4ba',
    storageBucket: 'todolist-ed4ba.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7xx4axqEDqEd2pVzCtbmDm0AyLM2-7YE',
    appId: '1:357686625509:web:3e911133026229b40d800c',
    messagingSenderId: '357686625509',
    projectId: 'todolist-ed4ba',
    authDomain: 'todolist-ed4ba.firebaseapp.com',
    storageBucket: 'todolist-ed4ba.firebasestorage.app',
  );

}